import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    container: { center: true, padding: "1rem", screens: { "2xl": "1280px" } },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        // 곁에 brand palette — warm Editorial Care (coral / sage / gold on cream)
        gt: {
          cream: "#FAF6EE",
          paper: "#F7F0E4",
          paper2: "#EDE3D1",
          coral: "#DC6B4A",
          coralDeep: "#B8543A",
          coralLight: "#F5DCC8",
          coralSoft: "#FBEEE0",
          sage: "#6B8B76",
          sageLight: "#DCE6DE",
          sageSoft: "#EEF3EF",
          gold: "#C4A053",
          goldSoft: "#F2E9D2",
          terra: "#9B5333",
          ink: "#1F1F1F",
          inkSoft: "#3D3D3D",
          muted: "#6E6657",
          mutedLight: "#A39B8C",
          line: "#E5DDCC",
          danger: "#CC3A3A",
          dangerSoft: "#FBE3E3",
        },
      },
      fontFamily: {
        serif: ["var(--font-serif)", "Gowun Batang", "Georgia", "serif"],
        sans: ["var(--font-sans)", "Gowun Dodum", "system-ui", "sans-serif"],
        display: ["var(--font-display)", "Cormorant Garamond", "serif"],
      },
      borderRadius: { lg: "var(--radius)", md: "calc(var(--radius) - 2px)", sm: "calc(var(--radius) - 4px)" },
      keyframes: {
        rise: { from: { opacity: "0", transform: "translateY(16px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "fade-in": { from: { opacity: "0" }, to: { opacity: "1" } },
        breathe: { "0%,100%": { transform: "translate(-50%,-50%) scale(1)", opacity: "0.5" }, "50%": { transform: "translate(-50%,-50%) scale(1.18)", opacity: "0.15" } },
        heartbeat: { "0%,100%": { transform: "scale(1)", opacity: "0.3" }, "50%": { transform: "scale(1.15)", opacity: "0" } },
        wave: { "0%,100%": { height: "30%", opacity: "0.4" }, "50%": { height: "100%", opacity: "1" } },
        blink: { "50%": { opacity: "0.3" } },
        typing: { "0%,60%,100%": { transform: "translateY(0)", opacity: "0.4" }, "30%": { transform: "translateY(-6px)", opacity: "1" } },
      },
      animation: {
        rise: "rise 0.6s ease both",
        "fade-in": "fade-in 0.8s ease both",
        breathe: "breathe 4s ease-in-out infinite",
        heartbeat: "heartbeat 2.4s ease-in-out infinite",
        wave: "wave 1.2s ease-in-out infinite",
        blink: "blink 1.2s ease-in-out infinite",
        typing: "typing 1.2s infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
export default config;
